### ISSUE TITLE
Map not sync

### ISSUE THREAD

**Issue by Erani0** [Mydayyy/Valheim-ServerSideMap#14]
I play on my server and not snyc wither map from other

**Comment by Mydayyy** [comment]
Greetings,

can you give more details? Is the plugin installed on the server and clients?

**Comment by Erani0** [comment]
Only Installed on Server you write ServerSide 
and this is only on Server not client 

Its self hostet On root

**Comment by Mydayyy** [comment]
It needs to be installed on the server and every client who wants to participate in sharing the map.

The server needs to inform the client of new map updates which is not possible if the client does not have this plugin (since by default valheim does not have events for that)

https://github.com/Mydayyy/Valheim-ServerSideMap#installation

> Installation
    Place the ServerSideMap.dll inside your BepInX plugin folder on your server and client
    Restart Server and Client

**Comment by Erani0** [comment]
Valheim ServerSideMap
This plugin moves the map to the server side. Meaning that, when someone else is exploring, your map will be updated too. This applies while being offline too. Once you connect, your explored map will be synced with the server and the server will sync everything to your local client. The server holds the explored map data in a new file which is saved and loaded along with the world.

As of right now, this only applies to the map exploration, not the set markers. Those will be shared too in a update soon to follow.

From [Thunderstore](https://valheim.thunderstore.io/package/Mydayyy/ServerSideMap/)

This information is needed for all not only here on github

**Comment by Mydayyy** [comment]
I will update the Thunderstore description
