### ISSUE TITLE
Mod stopped working with today's valheim update

### ISSUE THREAD

**Issue by ThatBulgarian** [Mydayyy/Valheim-ServerSideMap#32]
with the latest update to the client/server, the map mod has stopped working and isnt showing pins/updating the map discovery per player anymore.

**Comment by Mydayyy** [comment]
I'll look into it immediately after work.

Cheers
Mydayyy

**Comment by Mydayyy** [comment]
Greetings, 

I just did a quick test and it seems to still work? Can you share more details?

Cheers
Mydayyy

**Comment by ThatBulgarian** [comment]
Nevermind, I reinstalled the server/bepinex/serversidemap and now it all works. Sorry for the trouble
