### ISSUE TITLE
Cannot connect to server when mod is active, similar to #18

### ISSUE THREAD

**Issue by thesilverass** [Mydayyy/Valheim-ServerSideMap#33]
Hello. I'm running a server with several players and had been using your mod for the past 10 or so days without issue, it has improved our experience very much, so thank you!

Today I noticed that the Valheim service had been running out of memory and crashing, so I allocated more RAM to the server. After that I tried joining the server as a player only to be met with timeouts like those described in issue #18 . (I did not try connecting to the server in-game today before this so I'm unsure when the timeout problem began).

While troubleshooting with another player we observed that these timeout only occur while this mod (the only mod installed on the server) is active; removing the dll from the plugins folder allows us to connect. I also noticed that the .explored file on the server was 0 bytes; looking through world backups this appears to have changed some point between yesterday and today. There was quite a bit of exploring done yesterday so I'm wondering if this triggered some kind of issue with the file.

Unlike issue #18 , removing the .explored file and allowing the server to generate a new one does not allow us to connect.

I'm running on a Ubuntu 20.04.2 LTS server with the latest Valheim software and BepInEx packages installed, as well as 1.2.1 of ServerSideMap. I've attached the most recent copy of the .explored file I have before it went blank, from yesterday morning before the aforementioned exploring.

[Poopsylvannia.mod.serversidemap.zip](https://github.com/Mydayyy/Valheim-ServerSideMap/files/6201074/Poopsylvannia.mod.serversidemap.zip)

**Comment by Mydayyy** [comment]
Greetings,

only a quick question since I am on my lunchbreak right now:

Is you server updated to the latest valheim version that was released 2 days ago?

Cheers
Mydayyy

**Comment by thesilverass** [comment]
Yes I updated it to 0.148.6 on Tuesday morning

**Comment by Mydayyy** [comment]
Hmm, this is certainly strange. So far I havent been able to reproduce it, neither did I see any other reports regarding this.

> There was quite a bit of exploring done yesterday so I'm wondering if this triggered some kind of issue with the file.
This shouldn't cause an issue, since the exploration file is constant in size (apart from pins). So exploration does not cause the file to grow or shrink.

Is there any logout? Bepinex Log as well as the clientside Player.log file. Usually there is some form of error halting the connecting process when its appears to be stuck.
