### ISSUE TITLE
[Minor Typo] Typo in the generated config file

### ISSUE THREAD

**Issue by VP-EN** [Mydayyy/Valheim-ServerSideMap#34]
Hey Mydayyy, again, much thanks for the great mod. Appreciate it a lot 👍 

In the v1.3.0 generated config file, `eu.mydayyy.plugins.serversidemap.cfg`, the description still says:

> A local pin will not be uploaded if a pin exists in the given radius on the server (when using /convertpins **remove**localdupes)

It should be 

> A local pin will not be uploaded if a pin exists in the given radius on the server (when using /convertpins **ignore**localdupes)

**Comment by Mydayyy** [comment]
:facepalm: That's what I get for changing around the command name.

Thanks, I'll fix that

**Comment by VP-EN** [comment]
Nice and easy 😄
