### ISSUE TITLE
Broken since Update to Valheim 0.153.2

### ISSUE THREAD

**Issue by mirsch** [Mydayyy/Valheim-ServerSideMap#40]
Since update to Valheim 0.153.2 the mod seems to be broken.
We can see the map but it's not syncing new progress and all pins are gone.
Any ideas how to solve this?

**Comment by Mydayyy** [comment]
Greetings,

I did develop a new RC yesterday on the 0.153.2 patch and the mod still worked.
Can you check that the mod is loaded on the server as well as the client?

Best Regards
Mydayyy

**Comment by mirsch** [comment]
Sorry, BepInEx was not updated on the server
