### ISSUE TITLE
Feature request: Copy map pins from mod files to local

### ISSUE THREAD

**Issue by rakheepatel** [Mydayyy/Valheim-ServerSideMap#42]
I used this mod on a shared server with some friends (and it was immensely useful!), and while this mod was active I also played on my personal world. The shared world doesn't seem to have much activity now so there's no longer a need for a shared map. On removing this mod though all my map markers I added to my personal world since I installed this mod vanish unless I bring the mod back.

I suggest a feature to copy the map marker locations down into my world files.
Your suggestion of:

> My idea would be to implement a new command to sync pins from the server back to the client. Basically the opposite of the convertpins command.

would work just fine

**Comment by Mydayyy** [comment]
Greetings,

I uploaded a new RC: [https://github.com/Mydayyy/Valheim-ServerSideMap/releases/tag/rc-1.3.4](https://github.com/Mydayyy/Valheim-ServerSideMap/releases/tag/rc-1.3.4)

Please be adviced that this RC also contains rc-1.3.3 and rc-1.3.2.

This update adds a new command /downloadpins which should help you move your pins back.

Let me know if this works for you.

Best Regards
Mydayyy

**Comment by rakheepatel** [comment]
`/downloadpins` command seems to work just fine. It retained my markers after I took the mod off. Thank you!
