### ISSUE TITLE
Unable to Delete or Red X Markers with Mod

### ISSUE THREAD

**Issue by GhostParticle** [Mydayyy/Valheim-ServerSideMap#44]
Everything is working fine except for 2 things. 

- Old Markers cannot be deleted: You can create a new marker and delete it, but if you create a new marker, then leave the server and come back in, you cannot delete that marker, it is there permanently. 
- Unable to Red X markers: Once you place a marker, whether its new or old, you cannot place the red x on it. We use the red x feature to mark cleared dungeons. 

Neither of these issues came up until after H&H update. We removed the mod and were able to red x and delete new and old markers, the issue is only with this mod. I don't know if it is conflicting with another mod in some way as not all mods have updated for H&H, however all mods we currently have installed are working like were before the update, and we are using the same mods as before the update. 

Current Mods Installed - We do not have any other map mods installed
- BepInExPack
- EquimentAndQuickSlots
- CraftingWithContainers
- SimpleRecycling
- FarmGrid
- InstantMonsterLootDrop
- BiggerPicupRadius
- FloatingItems
- AutoFuel
- BiggerBoatMapExploreRadius

**Comment by Mydayyy** [comment]
Hello,

I tried to reproduce the issue on my server, but it is working for me.

Can you check both the server and the client logs for any errors and log output? When you delete or cross(X) a pin, the server should print a message:

```
[Info   :ServerSideMap] Client checked pin by server
[Info   :ServerSideMap] Server checked pin by client
[Info   :ServerSideMap] Client checked pin by server
[Info   :ServerSideMap] Server received pin by client
[Info   :ServerSideMap] Client received pin by server
```

Do those messages appear? Are there any errors? Is the log void of both?




In case the log is void of both, would you mind zipping me your plugins and config folder (making sure there are no sensitive data in the config folder) and sending those to me in order to try to reproduce the issue.

Best Regards
Mydayyy

**Comment by GhostParticle** [comment]
This is a very weird issue. It started working yesterday with no issues, then during gaming it all of a sudden stopped working again where i couldn't delete pins or red-x them. Today I jumped on and its working again no issues. Because the server was shut down i think the logs when it wasn't working was replaced. However, i did notice in some areas in the log showed connection failed right after the servermap info was logged. 

[Info   :ServerSideMap] loaded from existing explore file
[Warning: Unity Log] 09/21/2021 19:23:45: Game server connected failed
[Warning: Unity Log] 09/21/2021 19:24:08: Game server connected failed
[Warning: Unity Log] 09/21/2021 19:24:57: Game server connected failed

[Info   :ServerSideMap] Map saved. Pin Count: 76
[Info   : Unity Log] 09/21/2021 20:13:45:  Connections 0 ZDOS:386914  sent:0 recv:0
[Warning: Unity Log] 09/21/2021 20:22:08: Game server disconnected
[Warning: Unity Log] 09/21/2021 20:22:32: Game server connected failed
[Warning: Unity Log] 09/21/2021 20:22:56: Game server connected failed
[Info   : Unity Log] 09/21/2021 20:23:44:  Connections 0 ZDOS:386914  sent:0 recv:0
[Info   : Unity Log] 09/21/2021 20:23:45: clone 303
[Info   :ServerSideMap] Map saved. Pin Count: 76
[Warning: Unity Log] 09/21/2021 20:23:47: Game server connected failed
[Warning: Unity Log] 09/21/2021 20:25:08: Game server connected failed
[Warning: Unity Log] 09/21/2021 20:26:08: Game server connected failed
[Warning: Unity Log] 09/21/2021 20:30:59: Game server connected failed
[Info   : Unity Log] 09/21/2021 20:33:44:  Connections 0 ZDOS:386914  sent:0 recv:0

I will have to wait till it stops working again to get better logs if its even recognizing the pin check when deleting or red-xing the pin. Its working now as we speak but this is only the second time its worked since the update.

**Comment by GhostParticle** [comment]
This issue seems very random. Just did a test, was loaded in and some markers i could delete and red-x and some I could not. Waited for the world to save and jumped out, rebooted the server and jumped back in. Now i can edit all markers, even the ones I couldn't before the reboot of the server. I am getting the notification in the log when i edit the markers, and when i cant edit them there is no info in the log if it was tried and failed, its just doesn't record that.

**Comment by Mydayyy** [comment]
Okay, if the there are no notifications in the log file (were you checking the server logfile?), it seems that the client never even sends out the request to delete it. Could you provide me with the (plugins/configs).zip for the client as well as the server? I hope I may be able to reproduce the issue.

**Comment by GhostParticle** [comment]
Hello again, my apologies for getting back with you this late. I believe I have found the root cause of this issue. It seems to be a version difference. When H&H had dropped, we did not use your mod at the beginning, then you had dropped a test version in nexus in the comments section, I had pulled it from there. After a few days you published the current version in nexus and the thunderstore which is the one we are currently using. We are having no issues right now with pins made with that version, but all pins that were created from the test version I pulled from the comments section on nexus are the ones we cannot delete or red-x. I'm not sure why this is, but this seems to be the case. All pins created with the current version are fine, any pins created with the older/test version are not available to remove or red-x. I hope this information helps. I don't think its a bug with the mod, just  with the different versions. Let me know if you still need anything to look at or if you are good with this explanation. Thank You for your time and the mod.

**Comment by Mydayyy** [comment]
Greetings,

if you could upload me your .explored file (you can find it alongside your map savefile on your server) as well as take a screenshot of your map and circle me 2 or 3 pins which are not deletable, that would be great. That way I can check if those pins are actually on the server or somehow reside in your client.

**Comment by GhostParticle** [comment]
I also just went through a swamp and set multiple krypt pins. After doing so i went back to see if i could edit the pins and i could not.

**Comment by Mydayyy** [comment]
Hello,

please apologize the late reply.

I looked into the files you provided. The interesting parts:

- The markers in the crypt are definitely inside the file, so the server has knowledge of them.
- I was able to match some of the client "left click" log entries to the servers deleted/checked log entries
- When you reported, that the checking/deleting of pins did not work, I was not able to match the client "left click" logs to server entries
- This means, that the failure is entirely clientside, the client does not even send the event to the server
- This basically limits the failure possibilities to one function

I uploaded a new test file here. I would appreciate if you were able to give that a test. I removed one line which _might_ be responsible. Under normal circumstances this code would not be called but I can imagine that some mod is doing that. 

You only need to install the test version on your client, the server would not be affected by the change anyways. 

[ServerSideMap.zip](https://github.com/Mydayyy/Valheim-ServerSideMap/files/7253590/ServerSideMap.zip)

**Comment by NoisyFlake** [comment]
I'm having the same issue, so I just installed the new test version and will report back soon. Thanks for the quick help!

**Comment by GhostParticle** [comment]
Hello, I know this is several days later but I wanted to make sure I tested everything. Looks like the last test zip you gave me is working great, I can even delete or modify old pins created. So whatever change you made fixed the issue. I really appreciate your assistance with this. Thank you for the hard work on the MOD.

**Comment by Mydayyy** [comment]
Greetings,

thank you so much for bringing this to may attention.

Bit of context: The change I reverted was an earlier bugfix for a different issue. The change is clearing the local pin database when disconnecting from the server, so the pins do become stale in case you connect to a different server. Apparently it seems like some mod called a game function which in turn triggered the clearing of my local database.

I will now find a different way of fixing that bug and would upload another test version here. If you would be able to install  that too and just check if the issue crops up again that would be amazing.

If all goes well I would release the next test version as a new bugfix release.

Best Regards

**Comment by GhostParticle** [comment]
Do I need to put this in both client and server or just server side for now?

**Comment by GhostParticle** [comment]
Sounds good, thanks for the hard work on the mod.
