### ISSUE TITLE
Any way to reset mapshare?

### ISSUE THREAD

**Issue by randomsteve95370** [Mydayyy/Valheim-ServerSideMap#48]
Trying to figure out how to reset the map share. While setting up the server and config testing different mods I used the exploremap command to help me with testing and now I would like to be able to reset the map so the fully explored map doesnt get shared out to everyone who joins. 

I have tried resetting my own map with the "resetmap" and "resetsharedmap" commands. I have tried deleting the .explored files in the server as well and still no matter what when someone logs into the server their map gets set to fully explored. I've even tried uninstalling the mod and reinstalling after reseting the map. 

any way for me to fix this?

**Comment by vp-en** [comment]
You can use a tool like [Valheim Player Editor](https://www.nexusmods.com/valheim/mods/1536), and then remove all the maps that are saved to the character.

You would need to move your character from the Steam Cloud Saves to local storage, and then you can edit it from there. You can do this from ingame in Valheim, through "Manage Saves" or something like that, and then "Move to local storage".

Go to "Mapdata" and then just delete all the maps, and the character will have now have no map progress saved. Save the file, and then you can move the local character back to cloud saves again, if you want to.

Remember to delete the `explored` files as well, to reset the ServerSideMap synced map.

I hope it makes sense.

**Comment by Mydayyy** [comment]
Greetings,

vp-en pretty much gave the correct answer, I don't really have anything to add. As long as the correct `.explored` file is deleted, all exploration progress is gone. Make sure that the server is not running when you delete it tho, otherwise it most likely will get saved with the exploration progress again since it still exists in the memory.

Best Regards
