### ISSUE TITLE
Markers share but removed fog of war doesn't

### ISSUE THREAD

**Issue by hsramm** [Mydayyy/Valheim-ServerSideMap#49]
Pretty much what the title describes. The map markers are shared between players but the fog of war that is removed from one player isn't shared with the others. Any ideas?

**Comment by hsramm** [comment]
I just started using mods for the first time a few days ago so I can't comment on it working before. Yea, it's all enabled on the server side and client side.

**Comment by Mydayyy** [comment]
Greetings,

thank you. I will test the current version on the weekend and check whether it needs to be updated or if we need to find a configuration issue on the server

Best Regards

**Comment by hsramm** [comment]
I'm really not sure what happened but it started working a few days ago for the group so all good here!
