### ISSUE TITLE
Unable to remove some pins

### ISSUE THREAD

**Issue by Xanomenon** [Mydayyy/Valheim-ServerSideMap#53]
Some pins are able to be removed from the map after converting local pins, but random ones aren't.

**Comment by Mydayyy** [comment]
Greetings,

thank you for your report.

Can you help me understand the issue a little bit better?

You used the command `/convertpins`  and the pins got correctly uploaded to the server, but you can't remove the anymore?  Could you give me a step-list to reproduce this issue?

Best Regards
Mydayyy
