### ISSUE TITLE
Same issues that others have mentioned. 

### ISSUE THREAD

**Issue by LeHoop** [Mydayyy/Valheim-ServerSideMap#56]
First, thank you so much for looking into this issue. I am having what I believe to be the same issue. I deleted the .exe file, restarted server and am getting stuck on black screen after entering password. attached is my server log. I am not sure if having multiple logs helps at all, but I thought I would share it. 
 
[LogOutput.log](https://github.com/Mydayyy/Valheim-ServerSideMap/files/12425909/LogOutput.log)

**Comment by Mydayyy** [comment]
Greetings,

Thank you for your log files.

It should be solved by deleting the .explored files belonging to your world. In addition you can find a current beta version of the updated mod here: https://github.com/Mydayyy/Valheim-ServerSideMap/issues/55#issuecomment-1693368147

Best Regards
Mydayyy

**Comment by LeHoop** [comment]
Thank you. After installing your beta file, and removing the .exe file, I was able to log on. I am going to have my server group install it and I will update you on any successes or issues.

**Comment by Mydayyy** [comment]
1.3.9 released here, on nexusmods and thunderstore
