### ISSUE TITLE
strange conflict with valheimRAFT using this mod

### ISSUE THREAD

**Issue by s-slatcher** [Mydayyy/Valheim-ServerSideMap#61]
I wouldn't think these two would conflict, but I narrowed done the bug to just happening between this mod and the fork of valheimRAFT by zolantris on thunderstore. 

on reload, existing rafts will appear to break apart and become unusable, the main base of the raft will separate from the unique buildpieces like steering wheel and sails. 

edit: they will come back together just fine once serversidemap is disabled

**Comment by Mydayyy** [comment]
Greetings,

thank you for your report.

Are there any errors in your logfiles (Client or Server)?

Best Regards
Mydayyy
