### ISSUE TITLE
Cant get the Serversidemap to work

### ISSUE THREAD

**Issue by Maffinn** [Mydayyy/Valheim-ServerSideMap#62]
Hi, so im hosting a server and cant get the mod to work, i have it both server and client side, i tried everything from reinstalling it, changing configs etc. I could use some help. Thanks

**Comment by Mydayyy** [comment]
Greetings,

can you provide logs of your server and client?


Best Regards
Mydayyy

**Comment by Maffinn** [comment]
[LogOutput (3).log](https://github.com/Mydayyy/Valheim-ServerSideMap/files/14195634/LogOutput.3.log)
[LogOutput (2).log](https://github.com/Mydayyy/Valheim-ServerSideMap/files/14195636/LogOutput.2.log)
These are the logs, hopefully they r helpful.

**Comment by Mydayyy** [comment]
Greetings,

from the logs it looks like the mod is working on the client as well as the server. Can u confirm that it works if you create a second character and join the dedicated server. He should the exploration progress as well as the pins from the main character?

Best Regards
Mydayyy

**Comment by Maffinn** [comment]
Hello, i tried with a second character already and it wasnt working. Could it be that its not working because i've admined myself?

**Comment by Maffinn** [comment]
Could be, but my friend has the same modpack and it works for him, he sees me exploring and sees my pings, i just cant see any of his stuff

**Comment by Mydayyy** [comment]
Okay, that clears it up a little and is certainly strange. It means that the mod is working on the serverside correctly, it appears to just fail on your client.

Looking over your client logs again, while I see that ServerSideMap is loaded, it never outputs any event relating to receiving or creating a pin.

Can you doublecheck the ServerSideMap config?

**Comment by Maffinn** [comment]
Checked the config, the sharemap is set on true and the sharepin is share on true aswell. Though as far as i remember the mod did kinda stop working as soon as i interectred with a cartography table, but even on new characters the mod somehow doesnt work. Im not sure anymore.

**Comment by Maffinn** [comment]
![image](https://github.com/Mydayyy/Valheim-ServerSideMap/assets/93407327/e1f0f0cb-3dbe-40e0-b51e-3504c75784fe)
Not sure if it helps but saw this in the logs.

**Comment by Maffinn** [comment]
Hm okay, i will be trying out diffrent stuff and will keep you posted if i find a solution

**Comment by Maffinn** [comment]
![image](https://github.com/Mydayyy/Valheim-ServerSideMap/assets/93407327/dcd522c9-4d00-4f12-ab20-94b72b58bbd5)
I noticed that this isnt getting modified at all?

**Comment by Mydayyy** [comment]
That is the regular save file, it will be modified everytime the server map is saved

**Comment by Maffinn** [comment]
Shoudlnt it be saving everytime we explore new areas/place pings?

**Comment by Mydayyy** [comment]
Negative. It hooks the normal game function which saves the map, that file will always be written out alongside the normal valheim map.

It does keep everything you do in memory tho, but it will only be written to disk when the valheim world is saved

**Comment by Maffinn** [comment]
Hey i just read your description on github and it says the mod is incompatbile with playfab/crossplay. I would assume thats why it isnt working on my server?

**Comment by Mydayyy** [comment]
Greetings,

yes, that issue was reported a while ago to me so I documented it. Crossplay/PlayFab was introduced after this mod was written. From an earlier issue: https://github.com/Mydayyy/Valheim-ServerSideMap/issues/47#issuecomment-1426843264

**Comment by Maffinn** [comment]
Ah okay, id suggest adding this to the thunderstore page as it wouldve saved me alot of headache :D Is there any way to disable it on a server?

**Comment by Mydayyy** [comment]
> Ah okay, id suggest adding this to the thunderstore page as it wouldve saved me alot of headache :D Is there any way to disable it on a server?

I apologize, I will do that. I added it to the description locally, unfortunately I can only update the page when I release a new version. But with the next release the Known Issues will also be shown on the Thunderstore page.

Starting the server without crossplay used to be fairly straight forwards by omitting the `-crossplay` from the server args. 

> * Players can now use the parameter ‘-crossplay’ while running Dedicated servers to support crossplay. When using this parameter, the backend will be running Playfab instead of Steamworks. (A ‘Join code’ will appear when you join a Dedicated server supporting crossplay. Players can use this code to join the server. This Join code is regenerated whenever the server is restarted.)

I hope they didnt deprecate the steamwork network stack

**Comment by Maffinn** [comment]
Thanks!
